import javax.swing.*;
import java.awt.*;
import java.io.File;

public class EncryptGUI {
    private JButton fileButton;
    private JPanel rootPanel;

    public static void main(String[] args) {
        JFrame frame = new JFrame("加密程序");
        frame.setContentPane(new EncryptGUI().rootPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    public EncryptGUI() {
        fileButton.addActionListener(e -> {
            JFileChooser jFileChooser = new JFileChooser();
            jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            jFileChooser.showDialog(new Label(), "选择文件");

            File file = jFileChooser.getSelectedFile();
//            JOptionPane.showMessageDialog(rootPanel, file.getAbsolutePath());

            String newPath = file.getParentFile().getPath() + "/" + file.getName().replace(".mp4", "") + ".lsp";

            boolean flag = AESFileUtil.encryptFile
                    (file.getAbsolutePath(), newPath);
            System.out.println(flag ? ("加密完成：" + newPath) : "加密失败！");

            JOptionPane.showMessageDialog(rootPanel, flag ? "加密完成!" : "加密失败！");

//            flag = AESFileUtil.decryptFile
//                    (newPath, newPath + ".decrypt");
//            System.out.println(flag);
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        fileButton = new JButton();
        fileButton.setHorizontalAlignment(0);
        fileButton.setHorizontalTextPosition(0);
        fileButton.setMargin(new Insets(0, 0, 0, 0));
        fileButton.setMaximumSize(new Dimension(200, 80));
        fileButton.setMinimumSize(new Dimension(200, 80));
        fileButton.setPreferredSize(new Dimension(200, 80));
        fileButton.setText("选择文件");
        fileButton.setVerticalAlignment(0);
        rootPanel.add(fileButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

}
